# Always-available CPU pixels plus optional source-only decoder/input/services.
# Windows GDI is explicit, never a default display/capability. No configure/build
# downloads, encoder, assembly or runtime discovery of codec DLLs.
add_library(carplay_video_pixels STATIC src/carplay/projection_video_pixels.c)
target_include_directories(carplay_video_pixels PUBLIC src/carplay)
set_target_properties(carplay_video_pixels PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED ON)
if(MSVC)
  target_compile_options(carplay_video_pixels PRIVATE /W4)
else()
  target_compile_options(carplay_video_pixels PRIVATE -Wall -Wextra -Wpedantic)
endif()
add_executable(projection_video_pixels_tests tests/projection_video_pixels_tests.cpp tests/projection_video_pixels_c_api.c)
target_link_libraries(projection_video_pixels_tests PRIVATE carplay_video_pixels)
add_test(NAME projection_video_pixels_tests COMMAND projection_video_pixels_tests)
set_tests_properties(projection_video_pixels_tests PROPERTIES TIMEOUT 60)
set(CARPLAY_OPENH264_SOURCE "" CACHE PATH "Pinned OpenH264 2.6.0 checkout")
if(CARPLAY_OPENH264_SOURCE)
  find_package(Git REQUIRED)
  if(NOT IS_DIRECTORY "${CARPLAY_OPENH264_SOURCE}/.git")
    message(FATAL_ERROR "OpenH264 must be a pinned source checkout")
  endif()
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${CARPLAY_OPENH264_SOURCE}" rev-parse HEAD
    OUTPUT_VARIABLE _h264_head OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _h264_result)
  if(NOT _h264_result EQUAL 0 OR NOT _h264_head STREQUAL "652bdb7719f30b52b08e506645a7322ff1b2cc6f")
    message(FATAL_ERROR "OpenH264 2.6.0 commit mismatch")
  endif()
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${CARPLAY_OPENH264_SOURCE}" status
    --porcelain --untracked-files=all --ignored=matching
    OUTPUT_VARIABLE _h264_changed OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE _h264_result)
  if(NOT _h264_result EQUAL 0 OR NOT _h264_changed STREQUAL "")
    message(FATAL_ERROR "OpenH264 checkout changed; preserved, not overwritten")
  endif()
  execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${CARPLAY_OPENH264_SOURCE}" diff --quiet HEAD --
    RESULT_VARIABLE _h264_result)
  if(NOT _h264_result EQUAL 0)
    message(FATAL_ERROR "OpenH264 tracked source mismatch")
  endif()
  # Explicit generic C++ lists from the pinned common/decoder meson.build files.
  set(_h264_common common_tables copy_mb cpu crt_util_safe_x deblocking_common
    expand_pic intra_pred_common mc memory_align sad_common utils welsCodecTrace
    WelsTaskThread WelsThread WelsThreadLib WelsThreadPool)
  set(_h264_decoder au_parser bit_stream cabac_decoder deblocking decode_mb_aux
    decode_slice decoder decoder_core decoder_data_tables error_concealment fmo
    get_intra_predictor manage_dec_ref memmgr_nal_unit mv_pred parse_mb_syn_cabac
    parse_mb_syn_cavlc pic_queue rec_mb wels_decoder_thread)
  set(_h264_sources "${CARPLAY_OPENH264_SOURCE}/codec/decoder/plus/src/welsDecoderExt.cpp")
  foreach(_h264_file IN LISTS _h264_common)
    list(APPEND _h264_sources "${CARPLAY_OPENH264_SOURCE}/codec/common/src/${_h264_file}.cpp")
  endforeach()
  foreach(_h264_file IN LISTS _h264_decoder)
    list(APPEND _h264_sources "${CARPLAY_OPENH264_SOURCE}/codec/decoder/core/src/${_h264_file}.cpp")
  endforeach()
  find_package(Threads REQUIRED)
  add_library(carplay_openh264 STATIC ${_h264_sources})
  # Reviewed against all six decoder/common include sites: none reside beside
  # the upstream header, so this explicit first include directory is effective.
  # Portable native-endian memcpy replaces its unaligned integer-pointer casts.
  target_include_directories(carplay_openh264 BEFORE PRIVATE "${CMAKE_SOURCE_DIR}/third_party/openh264")
  target_include_directories(carplay_openh264 SYSTEM PUBLIC "${CARPLAY_OPENH264_SOURCE}/codec/api/wels"
    PRIVATE "${CARPLAY_OPENH264_SOURCE}/codec/common/inc"
    "${CARPLAY_OPENH264_SOURCE}/codec/decoder/core/inc"
    "${CARPLAY_OPENH264_SOURCE}/codec/decoder/plus/inc")
  target_link_libraries(carplay_openh264 PRIVATE Threads::Threads)
  if(MSVC)
    target_compile_definitions(carplay_openh264 PRIVATE _CRT_SECURE_NO_WARNINGS)
  endif()
  if(NOT WIN32)
    target_link_libraries(carplay_openh264 PRIVATE m)
  endif()
  add_library(carplay_h264 STATIC src/carplay/projection_h264.cpp)
  target_include_directories(carplay_h264 PUBLIC src/carplay)
  target_link_libraries(carplay_h264 PRIVATE carplay_openh264)
  if(MSVC)
    target_compile_options(carplay_h264 PRIVATE /W4 /permissive-)
  else()
    target_compile_options(carplay_h264 PRIVATE -Wall -Wextra -Wpedantic)
  endif()
  add_executable(projection_h264_tests tests/projection_h264_tests.cpp tests/projection_h264_c_api.c
    "${CARPLAY_OPENH264_SOURCE}/test/api/sha1.c")
  target_include_directories(projection_h264_tests PRIVATE "${CARPLAY_OPENH264_SOURCE}/test")
  target_link_libraries(projection_h264_tests PRIVATE carplay_h264)
  add_test(NAME projection_h264_tests COMMAND projection_h264_tests "${CARPLAY_OPENH264_SOURCE}/res")
  set_tests_properties(projection_h264_tests PROPERTIES TIMEOUT 60)
  add_executable(projection_h264_source_tests tests/projection_h264_source_tests.cpp)
  target_link_libraries(projection_h264_source_tests PRIVATE carplay_h264)
  add_test(NAME projection_h264_source_tests COMMAND projection_h264_source_tests "${CARPLAY_OPENH264_SOURCE}/res")
  set_tests_properties(projection_h264_source_tests PROPERTIES TIMEOUT 60)
  add_executable(projection_h264_source_limit_tests tests/projection_h264_source_limit_tests.cpp)
  target_link_libraries(projection_h264_source_limit_tests PRIVATE carplay_openh264)
  add_test(NAME projection_h264_source_limit_tests COMMAND projection_h264_source_limit_tests)
  set_tests_properties(projection_h264_source_limit_tests PROPERTIES TIMEOUT 60)
  if(TARGET carplay_monocypher)
    add_library(carplay_video STATIC src/carplay/projection_video.cpp)
    target_link_libraries(carplay_video PUBLIC carplay_h264 PRIVATE carplay_monocypher)
    if(MSVC)
      target_compile_options(carplay_video PRIVATE /W4 /permissive-)
    else()
      target_compile_options(carplay_video PRIVATE -Wall -Wextra -Wpedantic)
    endif()
    add_executable(projection_video_tests tests/projection_video_tests.cpp tests/projection_video_c_api.c
      "${CARPLAY_OPENH264_SOURCE}/test/api/sha1.c")
    target_include_directories(projection_video_tests PRIVATE "${CARPLAY_OPENH264_SOURCE}/test")
    target_link_libraries(projection_video_tests PRIVATE carplay_video carplay_monocypher)
    add_test(NAME projection_video_tests COMMAND projection_video_tests "${CARPLAY_OPENH264_SOURCE}/res")
    set_tests_properties(projection_video_tests PROPERTIES TIMEOUT 60)
    add_executable(projection_video_limit_tests tests/projection_video_limit_tests.cpp)
    target_link_libraries(projection_video_limit_tests PRIVATE carplay_h264 carplay_monocypher)
    add_test(NAME projection_video_limit_tests COMMAND projection_video_limit_tests)
    set_tests_properties(projection_video_limit_tests PROPERTIES TIMEOUT 60)
    if(WIN32 AND TARGET carplay_services)
      add_library(carplay_video_services STATIC src/carplay/projection_video_services_win.cpp)
      target_link_libraries(carplay_video_services PUBLIC carplay_video carplay_services)
      if(MSVC)
        target_compile_options(carplay_video_services PRIVATE /W4 /permissive-)
      else()
        target_compile_options(carplay_video_services PRIVATE -Wall -Wextra -Wpedantic)
      endif()
      add_executable(projection_video_services_tests tests/projection_video_services_tests.cpp tests/projection_video_services_c_api.c)
      target_link_libraries(projection_video_services_tests PRIVATE carplay_video_services carplay_receiver carplay_audio_services iphlpapi)
      add_test(NAME projection_video_services_tests COMMAND projection_video_services_tests
        "${CARPLAY_OPENH264_SOURCE}/res" "${CMAKE_SOURCE_DIR}/tests/fixtures/mfi-sap-vectors.txt"
        "${CMAKE_SOURCE_DIR}/tests/fixtures/pair-setup-vectors.txt" "${CMAKE_SOURCE_DIR}/tests/fixtures/projection-audio-vectors.txt"
        "${CMAKE_SOURCE_DIR}/tests/fixtures/projection-session-vectors.txt")
      set_tests_properties(projection_video_services_tests PROPERTIES TIMEOUT 60)
      add_library(carplay_video_gdi STATIC src/carplay/projection_video_gdi_win.cpp)
      target_link_libraries(carplay_video_gdi PUBLIC carplay_video_services carplay_video_pixels PRIVATE gdi32 user32)
      if(MSVC)
        target_compile_options(carplay_video_gdi PRIVATE /W4 /permissive-)
      else()
        target_compile_options(carplay_video_gdi PRIVATE -Wall -Wextra -Wpedantic)
      endif()
      add_executable(projection_video_gdi_tests tests/projection_video_gdi_tests.cpp tests/projection_video_gdi_c_api.c)
      target_link_libraries(projection_video_gdi_tests PRIVATE carplay_video_gdi)
      add_test(NAME projection_video_gdi_tests COMMAND projection_video_gdi_tests "${CARPLAY_OPENH264_SOURCE}/res")
      set_tests_properties(projection_video_gdi_tests PROPERTIES TIMEOUT 60)
    endif()
  endif()
endif()
