# Explicit optional source dependencies, prepared/verified by the media script.
# Configure/build never download or install a codec. Default receiver unchanged.
set(CARPLAY_OPUS_SOURCE "" CACHE PATH "Pinned Opus 1.6.1 checkout")
set(CARPLAY_FAAD_SOURCE "" CACHE PATH "Pinned FAAD2 2.11.3 checkout")
if(CARPLAY_OPUS_SOURCE OR CARPLAY_FAAD_SOURCE)
  if(NOT CARPLAY_OPUS_SOURCE OR NOT CARPLAY_FAAD_SOURCE OR NOT TARGET carplay_audio)
    message(FATAL_ERROR "Audio decoding requires both codec sources and the crypto audio target")
  endif()
  find_package(Git REQUIRED)
  function(carplay_verify_codec directory expected)
    if(NOT IS_DIRECTORY "${directory}/.git")
      message(FATAL_ERROR "Codec must be a pinned source checkout: ${directory}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${directory}" rev-parse HEAD
      OUTPUT_VARIABLE actual OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
    if(NOT result EQUAL 0 OR NOT actual STREQUAL expected)
      message(FATAL_ERROR "Codec commit mismatch: ${directory}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${directory}" status --porcelain --untracked-files=all --ignored=matching
      OUTPUT_VARIABLE changed OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result)
    if(NOT result EQUAL 0 OR NOT changed STREQUAL "")
      message(FATAL_ERROR "Codec source checkout changed: ${directory}")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${directory}" diff --quiet HEAD -- RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
      message(FATAL_ERROR "Codec tracked source mismatch: ${directory}")
    endif()
  endfunction()
  carplay_verify_codec("${CARPLAY_OPUS_SOURCE}" "22244de5a79bd1d6d623c32e72bf1954b56235be")
  carplay_verify_codec("${CARPLAY_FAAD_SOURCE}" "6918ebb51b8f7e86278da15884bd7114e4b9661e")
  # All seventeen negotiated formats, but no unnegotiated codec extensions.
  set(BUILD_SHARED_LIBS OFF)
  set(OPUS_BUILD_SHARED_LIBRARY OFF CACHE BOOL "" FORCE)
  set(OPUS_BUILD_TESTING OFF CACHE BOOL "" FORCE)
  set(OPUS_BUILD_PROGRAMS OFF CACHE BOOL "" FORCE)
  set(OPUS_CUSTOM_MODES OFF CACHE BOOL "" FORCE)
  set(OPUS_DISABLE_INTRINSICS ON CACHE BOOL "" FORCE)
  set(OPUS_FIXED_POINT OFF CACHE BOOL "" FORCE)
  set(OPUS_FLOAT_APPROX OFF CACHE BOOL "" FORCE)
  set(OPUS_FAST_MATH OFF CACHE BOOL "" FORCE)
  set(OPUS_HARDENING ON CACHE BOOL "" FORCE)
  set(OPUS_DEEP_PLC OFF CACHE BOOL "" FORCE)
  set(OPUS_DRED OFF CACHE BOOL "" FORCE)
  set(OPUS_OSCE OFF CACHE BOOL "" FORCE)
  set(OPUS_FUZZING OFF CACHE BOOL "" FORCE)
  set(OPUS_INSTALL_PKG_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
  set(OPUS_INSTALL_CMAKE_CONFIG_MODULE OFF CACHE BOOL "" FORCE)
  add_subdirectory("${CARPLAY_OPUS_SOURCE}" opus EXCLUDE_FROM_ALL)
  set(FAAD_BUILD_CLI OFF CACHE BOOL "" FORCE)
  set(FAAD_APPLY_DRC OFF CACHE BOOL "" FORCE)
  set(FAAD_BUNDLED_MODE ON)
  add_subdirectory("${CARPLAY_FAAD_SOURCE}" faad2 EXCLUDE_FROM_ALL)
  target_compile_definitions(faad PRIVATE LC_ONLY_DECODER DISABLE_SBR)
  add_library(carplay_decode STATIC src/carplay/projection_decode.c src/carplay/projection_decode_sink.c)
  set_target_properties(carplay_decode PROPERTIES C_STANDARD 99 C_STANDARD_REQUIRED ON)
  target_link_libraries(carplay_decode PUBLIC carplay_audio PRIVATE opus faad)
  if(MSVC)
    target_compile_options(carplay_decode PRIVATE /W4)
  else()
    target_compile_options(carplay_decode PRIVATE -Wall -Wextra -Wpedantic)
  endif()
  add_executable(projection_decode_tests tests/projection_decode_tests.cpp)
  target_link_libraries(projection_decode_tests PRIVATE carplay_decode)
  add_test(NAME projection_decode_tests COMMAND projection_decode_tests "${CMAKE_SOURCE_DIR}/tests/fixtures/projection-codec-vectors.txt")
  if(TARGET carplay_wasapi)
    add_executable(projection_decode_services_tests tests/projection_decode_services_tests.cpp)
    target_link_libraries(projection_decode_services_tests PRIVATE carplay_decode carplay_wasapi carplay_audio_services)
    add_test(NAME projection_decode_services_tests COMMAND projection_decode_services_tests "${CMAKE_SOURCE_DIR}/tests/fixtures/projection-codec-vectors.txt")
  endif()
endif()
